# Generated by Django 5.2.6 on 2025-09-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenserunits',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='gununit',
            name='deleted_at',
        ),
    ]
