# Generated by Django 5.2.6 on 2025-09-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0002_remove_dispenserunits_deleted_at_and_more'),
        ('existing_tables', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingUsersProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('existing_tables.users',),
        ),
    ]
