# Generated by Django 5.2.6 on 2025-09-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0003_existingusersproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GunUnit',
        ),
    ]
