# Generated by Django 5.2.6 on 2025-09-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0005_gununits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gununits',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gununits',
            name='updated_at',
        ),
    ]
