# Generated by Django 5.2.6 on 2025-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0006_remove_gununits_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gununits',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gununits',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
