# Generated by Django 5.2.6 on 2025-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0007_gununits_created_at_gununits_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeUnits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imei_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('hardware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_capacity', models.IntegerField(blank=True, help_text='mAh', null=True)),
                ('backup_hours', models.FloatField(blank=True, help_text='Estimated backup in hours', null=True)),
                ('assigned_status', models.BooleanField(default=False)),
                ('connectivity_status', models.CharField(blank=True, db_comment='online/offline/unknown', max_length=12, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_units',
            },
        ),
    ]
