# Generated by Django 5.2.6 on 2025-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0008_nodeunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='gununits',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeunits',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
