# Generated by Django 5.2.6 on 2025-09-25 11:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0009_gununits_production_date_nodeunits_production_date'),
        ('existing_tables', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser_Gun_Mapping_To_Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('totalizer_reading', models.FloatField(default=0.0, help_text='Totalizer reading value at the time of assigning the dispenser-gun pair to the customer', validators=[django.core.validators.MaxValueValidator(99999999.0)])),
                ('live_totalizer_reading', models.FloatField(default=0.0, help_text='Live totalizer reading value', validators=[django.core.validators.MaxValueValidator(99999999.0)])),
                ('total_reading_amount', models.FloatField(default=0.0, help_text='Total amount collected at the time of assigning the dispenser-gun pair to the customer')),
                ('live_total_reading_amount', models.FloatField(default=0.0, help_text='Live total amount collected so far')),
                ('live_price', models.FloatField(default=0.0, help_text='Current price per liter/unit')),
                ('grade', models.IntegerField(blank=True, help_text='Fuel grade/type', null=True)),
                ('nozzle', models.IntegerField(blank=True, help_text='Nozzle number', null=True)),
                ('gps_coordinates', models.JSONField(blank=True, help_text="Live GPS coordinates as JSON: {'lat': ..., 'lon': ...}", null=True)),
                ('assigned_status', models.BooleanField(default=True, help_text='Whether this unit is currently with customer or not')),
                ('status', models.BooleanField(default=True, help_text='to stop controls to the customer')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='existing_tables.customers')),
                ('dispenser_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT_Panel.dispenserunits')),
                ('gun_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT_Panel.gununits')),
            ],
            options={
                'verbose_name': 'Dispenser-Gun Mapping to Customer',
                'verbose_name_plural': 'Dispenser-Gun Mappings',
                'db_table': 'dispenser_gun_mapping_to_customer',
            },
        ),
    ]
