# Generated by Django 5.2.6 on 2025-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0011_alter_dispenser_gun_mapping_to_customer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenser_gun_mapping_to_customer',
            name='customer',
            field=models.BigIntegerField(help_text='Customer ID'),
        ),
    ]
