# Generated by Django 5.2.6 on 2025-09-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0012_alter_dispenser_gun_mapping_to_customer_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDispenserCustomerMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer', models.BigIntegerField(help_text='Customer ID to whom both units are assigned')),
                ('fuel_sensor_type', models.IntegerField(help_text='Fuel sensor type, e.g., 0 - ultrasonic, 1 - float, 2 - capacitive')),
                ('assigned_status', models.BooleanField(default=True, help_text='Whether this unit is currently with customer or not')),
                ('status', models.BooleanField(default=True, help_text='to stop controls to the customer')),
                ('gps_coordinates', models.JSONField(blank=True, help_text="Live GPS coordinates as JSON: {'lat': ..., 'lon': ...}", null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dispenser_unit', models.ForeignKey(blank=True, help_text='Dispenser Unit (optional) being assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenser_mappings', to='IoT_Panel.dispenserunits')),
                ('node_unit', models.ForeignKey(help_text='Node Unit being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='node_mappings', to='IoT_Panel.nodeunits')),
            ],
            options={
                'verbose_name': 'Node-Dispenser Mapping to Customer',
                'verbose_name_plural': 'Node-Dispenser Mappings',
                'db_table': 'node_dispenser_customer_mapping',
            },
        ),
    ]
