# Generated by Django 5.2.6 on 2025-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0013_nodedispensercustomermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation_Mapping_DispenserUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_location_id', models.BigIntegerField(help_text='Delivery Location ID where dispenser unit is installed')),
                ('DU_Accessible_delivery_locations', models.JSONField(default=list, help_text='Stores a list of delivery location IDs of this customer who can access this dispenser unit')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery Location Mapping Dispenser Unit',
                'verbose_name_plural': 'Delivery Location Mappings',
                'db_table': 'delivery_location_mapping_dispenser_unit',
            },
        ),
    ]
