# Generated by Django 5.2.6 on 2025-09-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0014_deliverylocation_mapping_dispenserunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation_mapping_dispenserunit',
            name='DU_Unaccessible_delivery_locations',
            field=models.JSONField(default=list, help_text='Stores a list of delivery location IDs of this customer who cannot access this dispenser unit temporarily'),
        ),
    ]
