# Generated by Django 5.2.6 on 2025-09-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0015_deliverylocation_mapping_dispenserunit_du_unaccessible_delivery_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation_mapping_dispenserunit',
            name='DU_Unaccessible_delivery_locations',
        ),
    ]
