# Generated by Django 5.2.6 on 2025-09-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0016_remove_deliverylocation_mapping_dispenserunit_du_unaccessible_delivery_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation_mapping_dispenserunit',
            name='dispenser_gun_mapping_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IoT_Panel.dispenser_gun_mapping_to_customer'),
        ),
    ]
