# Generated by Django 5.2.6 on 2025-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0017_deliverylocation_mapping_dispenserunit_dispenser_gun_mapping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='connectivity_status',
            field=models.BooleanField(default=False, help_text='Whether the machine is connected to the websocket server or not'),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='machine_status',
            field=models.IntegerField(choices=[(1, 'Idle'), (0, 'Offline'), (2, 'Dispensing'), (3, 'Allocated'), (4, 'Error')], default=0, help_text='Machine status'),
        ),
    ]
