# Generated by Django 5.2.6 on 2025-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0018_dispenser_gun_mapping_to_customer_connectivity_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFuelDispensingDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(help_text='User ID of who is requesting the fuel dispensing')),
                ('user_name', models.CharField(help_text='User Name', max_length=255)),
                ('user_email', models.EmailField(help_text='User Email', max_length=254)),
                ('user_phone', models.CharField(help_text='User Phone', max_length=255)),
                ('dispenser_gun_mapping_id', models.BigIntegerField(help_text='Dispenser Gun Mapping ID')),
                ('dispenser_serialnumber', models.CharField(help_text='Dispenser Unit Serial Number', max_length=255)),
                ('dispenser_imeinumber', models.CharField(help_text='Dispenser Unit IMEI Number', max_length=255)),
                ('delivery_location_id', models.BigIntegerField(help_text='Delivery Location ID of the dispenser unit')),
                ('delivery_location_name', models.CharField(help_text='Delivery Location Name', max_length=255)),
                ('DU_Accessible_delivery_locations', models.JSONField(default=list, help_text='list of delivery location IDs which are accessible to the selected dispenser unit')),
                ('customer_id', models.BigIntegerField(help_text='Customer ID')),
                ('customer_name', models.CharField(help_text='Customer Name', max_length=255)),
                ('customer_email', models.EmailField(help_text='Customer Email', max_length=254)),
                ('customer_phone', models.CharField(help_text='Customer Phone', max_length=255)),
                ('asset_id', models.BigIntegerField(help_text='Asset ID')),
                ('asset_name', models.CharField(help_text='Asset Name', max_length=255)),
                ('asset_tag_id', models.CharField(help_text='Asset Tag ID', max_length=255)),
                ('asset_tag_type', models.CharField(help_text='Asset Tag Type', max_length=255)),
                ('asset_type', models.CharField(help_text='Asset Type', max_length=255)),
                ('transaction_id', models.CharField(help_text='Transaction ID', max_length=255)),
                ('dispenser_volume', models.FloatField(help_text='Dispenser Volume')),
                ('dispenser_price', models.FloatField(help_text='Dispenser Price')),
                ('dispenser_live_price', models.FloatField(help_text='Dispenser Live Price')),
                ('request_type', models.IntegerField(choices=[(0, 'Volume'), (1, 'Amount')], default=0, help_text='Request Type')),
                ('request_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0, help_text='Request Status')),
                ('fuel_state', models.BooleanField(default=False)),
                ('transaction_log', models.JSONField(blank=True, help_text='log of the transaction', null=True)),
                ('request_created_at', models.DateTimeField(blank=True, null=True)),
                ('request_updated_at', models.DateTimeField(blank=True, null=True)),
                ('request_created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('request_updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Request Fuel Dispensing Details',
                'verbose_name_plural': 'Request Fuel Dispensing Details',
                'db_table': 'request_fuel_dispensing_details',
            },
        ),
    ]
