# Generated by Django 5.2.6 on 2025-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0019_requestfueldispensingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='remarks',
            field=models.CharField(blank=True, help_text='Remarks', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='DU_Accessible_delivery_locations',
            field=models.JSONField(blank=True, default=list, help_text='list of delivery location IDs which are accessible to the selected dispenser unit', null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_name',
            field=models.CharField(blank=True, help_text='Asset Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_tag_id',
            field=models.CharField(blank=True, help_text='Asset Tag ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_tag_type',
            field=models.CharField(blank=True, help_text='Asset Tag Type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_type',
            field=models.CharField(blank=True, help_text='Asset Type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer Phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='dispenser_live_price',
            field=models.FloatField(blank=True, help_text='Dispenser Live Price', null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='dispenser_price',
            field=models.FloatField(blank=True, help_text='Dispenser Price', null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='dispenser_volume',
            field=models.FloatField(blank=True, help_text='Dispenser Volume', null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='user_email',
            field=models.EmailField(blank=True, help_text='User Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='user_name',
            field=models.CharField(blank=True, help_text='User Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='user_phone',
            field=models.CharField(blank=True, help_text='User Phone', max_length=255, null=True),
        ),
    ]
