# Generated by Django 5.2.6 on 2025-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0020_requestfueldispensingdetails_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='dispenser_received_price',
            field=models.FloatField(blank=True, help_text='Dispenser Received Price', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='dispenser_received_volume',
            field=models.FloatField(blank=True, help_text='Dispenser Received Volume', null=True),
        ),
    ]
