# Generated by Django 5.2.6 on 2025-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0021_requestfueldispensingdetails_dispenser_received_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='dispense_end_time',
            field=models.DateTimeField(blank=True, help_text='Fuel Dispense End Time', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='dispense_status_code',
            field=models.IntegerField(default=0, help_text='Fuel Dispenser Status Code'),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='dispense_time_taken',
            field=models.FloatField(blank=True, help_text='Fuel Dispense Time Taken in seconds', null=True),
        ),
    ]
