# Generated by Django 5.2.6 on 2025-10-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0022_requestfueldispensingdetails_dispense_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Hardware Received'), (2, 'Dispensiing'), (3, 'Completed'), (4, 'Interrupted'), (5, 'Failed')], default=0, help_text='Request Status'),
        ),
    ]
