# Generated by Django 5.2.6 on 2025-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0023_alter_requestfueldispensingdetails_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIN_Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=255)),
                ('customer_id', models.BigIntegerField(help_text='Customer ID')),
                ('delivery_location_id', models.JSONField(default=list, help_text='Delivery Location ID')),
                ('point_of_contact_id', models.JSONField(default=list, help_text='Point of Contact ID')),
                ('vehicle_type', models.CharField(blank=True, help_text='Vehicle Type from Assets Type Table', max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Capacity', null=True)),
                ('dg_kv', models.BigIntegerField(blank=True, help_text='DG KV if type is Diesel Generator', null=True)),
                ('tag_type', models.CharField(blank=True, choices=[(1, 'None'), (2, 'RFID'), (3, 'NFC')], help_text='Tag Type', max_length=255, null=True)),
                ('tag_id', models.CharField(blank=True, help_text='Tag ID', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, help_text='Remarks', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'VIN Vehicle',
                'verbose_name_plural': 'VIN Vehicles',
                'db_table': 'vin_vehicle',
            },
        ),
    ]
