# Generated by Django 5.2.6 on 2025-10-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0024_vin_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin_vehicle',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vin_vehicle',
            name='vehicle_type_name',
            field=models.CharField(blank=True, help_text='Vehicle Type Name from Assets Type Table', max_length=255, null=True),
        ),
    ]
