# Generated by Django 5.2.6 on 2025-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0025_vin_vehicle_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vin_vehicle',
            name='remarks',
        ),
        migrations.AddField(
            model_name='vin_vehicle',
            name='buffer_dispense_volume',
            field=models.FloatField(blank=True, help_text='buffer dispense volume given to this vin', null=True),
        ),
        migrations.AddField(
            model_name='vin_vehicle',
            name='buffer_reason',
            field=models.CharField(blank=True, help_text='Reason to allocate the buffer volume', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vin_vehicle',
            name='dispense_volume',
            field=models.FloatField(blank=True, help_text='max dispense volume given to this vin', null=True),
        ),
    ]
