# Generated by Django 5.2.6 on 2025-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0026_remove_vin_vehicle_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin_vehicle',
            name='status',
            field=models.BooleanField(default=False, help_text='whether this vin is used or not once'),
        ),
    ]
