# Generated by Django 5.2.6 on 2025-10-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0027_vin_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_id',
            field=models.BigIntegerField(help_text='Asset ID / VIN ID'),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_name',
            field=models.CharField(blank=True, help_text='Asset Name /VIN Name', max_length=255, null=True),
        ),
    ]
