# Generated by Django 5.2.6 on 2025-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0028_alter_requestfueldispensingdetails_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='request_vehicle',
            field=models.IntegerField(choices=[(0, 'Asset'), (1, 'VIN')], default=0, help_text='Request Vehicle'),
        ),
    ]
