# Generated by Django 5.2.6 on 2025-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0029_requestfueldispensingdetails_request_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='gps_coordinates_ending',
            field=models.JSONField(blank=True, help_text="GPS coordinates at transaction ending as JSON: {'lat': ..., 'lon': ...}", null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='gps_coordinates_starting',
            field=models.JSONField(blank=True, help_text="GPS coordinates at transaction starting as JSON: {'lat': ..., 'lon': ...}", null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='totalizer_price_ending',
            field=models.FloatField(blank=True, help_text='Totalizer Price at transaction ending', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='totalizer_price_starting',
            field=models.FloatField(blank=True, help_text='Totalizer Price at transaction starting', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='totalizer_validation',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False')], default=0, help_text='Totalizer Reading Validation with previous transaction'),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='totalizer_volume_ending',
            field=models.FloatField(blank=True, help_text='Totalizer Volume at transaction ending', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='totalizer_volume_starting',
            field=models.FloatField(blank=True, help_text='Totalizer Volume at transaction starting', null=True),
        ),
    ]
