# Generated by Django 5.2.6 on 2025-10-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0030_requestfueldispensingdetails_gps_coordinates_ending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='totalizer_validation',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'Pending')], default=2, help_text='Totalizer Reading Validation with previous transaction'),
        ),
    ]
