# Generated by Django 5.2.6 on 2025-12-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0031_alter_requestfueldispensingdetails_totalizer_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='fuel_level_sensor',
            field=models.BooleanField(default=False, help_text='Whether the tank is installed with fuel level sensor or not'),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='fuel_level_sensor_brand',
            field=models.CharField(blank=True, db_comment='Brand of the Fuel Level Sensor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='fuel_level_sensor_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Capacitive')], default=0, help_text='Fuel Level Sensor Type'),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='installation_mode',
            field=models.IntegerField(choices=[(0, 'Static'), (1, 'Mobility')], default=0, help_text='Installation Mode'),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='tank_capacity',
            field=models.FloatField(blank=True, help_text='Tank Capacity', null=True),
        ),
        migrations.AlterField(
            model_name='dispenser_gun_mapping_to_customer',
            name='gun_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IoT_Panel.gununits'),
        ),
    ]
