# Generated by Django 5.2.6 on 2026-01-19 05:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0032_dispenser_gun_mapping_to_customer_fuel_level_sensor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser_Gun_Mapping_To_Vehicles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle', models.BigIntegerField(blank=True, help_text='Vehicle ID', null=True)),
                ('totalizer_reading', models.FloatField(default=0.0, help_text='Totalizer reading value at the time of assigning the dispenser-gun pair to the customer', validators=[django.core.validators.MaxValueValidator(99999999.0)])),
                ('live_totalizer_reading', models.FloatField(default=0.0, help_text='Live totalizer reading value', validators=[django.core.validators.MaxValueValidator(99999999.0)])),
                ('total_reading_amount', models.FloatField(default=0.0, help_text='Total amount collected at the time of assigning the dispenser-gun pair to the customer')),
                ('live_total_reading_amount', models.FloatField(default=0.0, help_text='Live total amount collected so far')),
                ('live_price', models.FloatField(default=0.0, help_text='Current price per liter/unit')),
                ('grade', models.IntegerField(blank=True, help_text='Fuel grade/type', null=True)),
                ('nozzle', models.IntegerField(blank=True, help_text='Nozzle number', null=True)),
                ('dispenser_position', models.CharField(blank=True, help_text='Dispenser Position', max_length=255, null=True)),
                ('gps_coordinates', models.JSONField(blank=True, help_text="Live GPS coordinates as JSON: {'lat': ..., 'lon': ...}", null=True)),
                ('assigned_status', models.BooleanField(default=True, help_text='Whether this unit is currently with customer or not')),
                ('status', models.BooleanField(default=True, help_text='to stop controls to the customer')),
                ('machine_status', models.IntegerField(choices=[(1, 'Idle'), (0, 'Offline'), (2, 'Dispensing'), (3, 'Allocated'), (4, 'Error')], default=0, help_text='Machine status')),
                ('connectivity_status', models.BooleanField(default=False, help_text='Whether the machine is connected to the websocket server or not')),
                ('installation_mode', models.IntegerField(choices=[(0, 'Static'), (1, 'Mobility')], default=0, help_text='Installation Mode')),
                ('fuel_level_sensor', models.BooleanField(default=False, help_text='Whether the tank is installed with fuel level sensor or not')),
                ('fuel_level_sensor_type', models.IntegerField(choices=[(0, 'None'), (1, 'Capacitive')], default=0, help_text='Fuel Level Sensor Type')),
                ('fuel_level_sensor_brand', models.CharField(blank=True, db_comment='Brand of the Fuel Level Sensor', max_length=100, null=True)),
                ('tank_capacity', models.FloatField(blank=True, help_text='Tank Capacity', null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dispenser_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT_Panel.dispenserunits')),
                ('gun_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IoT_Panel.gununits')),
            ],
            options={
                'verbose_name': 'Dispenser-Gun Mapping to Vehicles',
                'verbose_name_plural': 'Dispenser-Gun Mappings to Vehicles',
                'db_table': 'dispenser_gun_mapping_to_vehicles',
            },
        ),
    ]
