# Generated by Django 5.2.6 on 2026-01-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0033_dispenser_gun_mapping_to_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='dispenser_position',
        ),
    ]
