# Generated by Django 5.2.6 on 2026-01-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0034_remove_dispenser_gun_mapping_to_vehicles_dispenser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='dispenser_position',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right'), (2, 'Center')], default=0, help_text='Dispenser Position'),
        ),
    ]
