# Generated by Django 5.2.6 on 2026-01-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0035_dispenser_gun_mapping_to_vehicles_dispenser_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFuelDispensingDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_id', models.BigIntegerField(help_text='Driver ID of who is requesting the fuel dispensing')),
                ('driver_name', models.CharField(blank=True, help_text='Driver Name', max_length=255, null=True)),
                ('driver_email', models.EmailField(blank=True, help_text='Driver Email', max_length=254, null=True)),
                ('driver_phone', models.CharField(blank=True, help_text='Driver Phone', max_length=255, null=True)),
                ('dispenser_gun_mapping_id', models.BigIntegerField(help_text='Dispenser Gun Mapping ID assigned to the vehicle')),
                ('dispenser_serialnumber', models.CharField(help_text='Dispenser Unit Serial Number', max_length=255)),
                ('dispenser_imeinumber', models.CharField(help_text='Dispenser Unit IMEI Number', max_length=255)),
                ('vehicle_id', models.BigIntegerField(help_text='Vehicle ID')),
                ('route_plan_details_id', models.BigIntegerField(help_text='Route Plan Details ID')),
                ('route_plan_id', models.BigIntegerField(help_text='Route Plan ID')),
                ('total_ordered_quantity', models.FloatField(blank=True, help_text='Total Ordered Quantity', null=True)),
                ('remaining_quantity_dispensed', models.FloatField(blank=True, help_text='Remaining Quantity that should be dispensed in this order', null=True)),
                ('order_id', models.BigIntegerField(help_text='Order ID')),
                ('asset_id', models.BigIntegerField(help_text='Asset ID / VIN ID')),
                ('asset_name', models.CharField(blank=True, help_text='Asset Name', max_length=255, null=True)),
                ('asset_tag_id', models.CharField(blank=True, help_text='Asset Tag ID', max_length=255, null=True)),
                ('asset_tag_type', models.CharField(blank=True, help_text='Asset Tag Type', max_length=255, null=True)),
                ('asset_type', models.CharField(blank=True, help_text='Asset Type', max_length=255, null=True)),
                ('transaction_id', models.CharField(help_text='Transaction ID', max_length=255)),
                ('dispenser_volume', models.FloatField(blank=True, help_text='Dispenser Volume', null=True)),
                ('dispenser_price', models.FloatField(blank=True, help_text='Dispenser Price', null=True)),
                ('dispenser_live_price', models.FloatField(blank=True, help_text='Dispenser Live Price', null=True)),
                ('dispenser_received_volume', models.FloatField(blank=True, help_text='Dispenser Received Volume', null=True)),
                ('dispenser_received_price', models.FloatField(blank=True, help_text='Dispenser Received Price', null=True)),
                ('totalizer_volume_starting', models.FloatField(blank=True, help_text='Totalizer Volume at transaction starting', null=True)),
                ('totalizer_volume_ending', models.FloatField(blank=True, help_text='Totalizer Volume at transaction ending', null=True)),
                ('totalizer_price_starting', models.FloatField(blank=True, help_text='Totalizer Price at transaction starting', null=True)),
                ('totalizer_price_ending', models.FloatField(blank=True, help_text='Totalizer Price at transaction ending', null=True)),
                ('gps_coordinates_starting', models.JSONField(blank=True, help_text="GPS coordinates at transaction starting as JSON: {'lat': ..., 'lon': ...}", null=True)),
                ('gps_coordinates_ending', models.JSONField(blank=True, help_text="GPS coordinates at transaction ending as JSON: {'lat': ..., 'lon': ...}", null=True)),
                ('totalizer_validation', models.IntegerField(choices=[(0, 'True'), (1, 'False'), (2, 'Pending')], default=2, help_text='Totalizer Reading Validation with previous transaction')),
                ('request_type', models.IntegerField(choices=[(0, 'Volume'), (1, 'Amount')], default=0, help_text='Request Type')),
                ('request_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Hardware Received'), (2, 'Dispensiing'), (3, 'Completed'), (4, 'Interrupted'), (5, 'Failed')], default=0, help_text='Request Status')),
                ('fuel_state', models.BooleanField(default=False)),
                ('transaction_log', models.JSONField(blank=True, help_text='log of the transaction', null=True)),
                ('dispense_end_time', models.DateTimeField(blank=True, help_text='Fuel Dispense End Time', null=True)),
                ('dispense_time_taken', models.FloatField(blank=True, help_text='Fuel Dispense Time Taken in seconds', null=True)),
                ('dispense_status_code', models.IntegerField(default=0, help_text='Fuel Dispenser Status Code')),
                ('remarks', models.CharField(blank=True, help_text='Remarks', max_length=255, null=True)),
                ('request_created_at', models.DateTimeField(blank=True, null=True)),
                ('request_updated_at', models.DateTimeField(blank=True, null=True)),
                ('request_created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('request_updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order Fuel Dispensing Details',
                'verbose_name_plural': 'Order Fuel Dispensing Details',
                'db_table': 'order_fuel_dispensing_details',
            },
        ),
        migrations.AlterField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='assigned_status',
            field=models.BooleanField(default=True, help_text='Whether this unit is currently with vehicles or not'),
        ),
        migrations.AlterField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='status',
            field=models.BooleanField(default=True, help_text='to stop controls to the vehicles'),
        ),
    ]
