# Generated by Django 5.2.6 on 2026-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0036_orderfueldispensingdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='delivery_location_id',
            field=models.BigIntegerField(blank=True, help_text='Delivery Location ID', null=True),
        ),
    ]
