# Generated by Django 5.2.6 on 2026-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0037_orderfueldispensingdetails_delivery_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfueldispensingdetails',
            name='asset_id',
            field=models.BigIntegerField(help_text='Asset ID'),
        ),
    ]
