# Generated by Django 5.2.6 on 2026-01-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0038_alter_orderfueldispensingdetails_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer Email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='customer_id',
            field=models.BigIntegerField(blank=True, help_text='Customer ID', null=True),
        ),
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer Phone', max_length=255, null=True),
        ),
    ]
