# Generated by Django 5.2.6 on 2026-01-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0039_orderfueldispensingdetails_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfueldispensingdetails',
            name='asset_id',
            field=models.BigIntegerField(blank=True, help_text='Asset ID', null=True),
        ),
    ]
