# Generated by Django 5.2.6 on 2026-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0040_alter_orderfueldispensingdetails_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='buffer_reason',
            field=models.CharField(blank=True, help_text='Reason to allocate the buffer volume', max_length=255, null=True),
        ),
    ]
