# Generated by Django 5.2.6 on 2026-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0041_orderfueldispensingdetails_buffer_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='fuel_level_configuration',
            field=models.JSONField(blank=True, db_comment='Configuration of the Fuel Level Sensor', null=True),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='fuel_level_sensor_description',
            field=models.CharField(blank=True, db_comment='Description of the Fuel Level Sensor', max_length=111255, null=True),
        ),
    ]
