# Generated by Django 5.2.6 on 2026-02-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0043_dispenser_gun_mapping_to_customer_fuel_level_sensor_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='user_tag',
            field=models.CharField(blank=True, help_text='User Tag', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='asset_id',
            field=models.BigIntegerField(blank=True, help_text='Asset ID / VIN ID', null=True),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='request_vehicle',
            field=models.IntegerField(choices=[(0, 'Asset'), (1, 'VIN'), (2, 'User')], default=0, help_text='Request Vehicle'),
        ),
    ]
