# Generated by Django 5.2.6 on 2026-02-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0044_requestfueldispensingdetails_user_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfueldispensingdetails',
            name='user_tag',
        ),
        migrations.CreateModel(
            name='FuelSensorReadings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, help_text='Fuel temperature in degree Celsius', null=True)),
                ('fuel_level', models.FloatField(blank=True, help_text='Fuel level reading', null=True)),
                ('data_type', models.IntegerField(choices=[(41, 'Transaction Data'), (31, '30 Sec Auto Push')], help_text='41 - Transaction Data, 31 - 30 sec Auto Push')),
                ('reading_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when data is stored')),
                ('dispenser_customer_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_readings_customer', to='IoT_Panel.dispenser_gun_mapping_to_customer')),
                ('dispenser_vehicle_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_readings_vehicle', to='IoT_Panel.dispenser_gun_mapping_to_vehicles')),
            ],
            options={
                'verbose_name': 'Fuel Sensor Reading',
                'verbose_name_plural': 'Fuel Sensor Readings',
                'db_table': 'fuel_sensor_readings',
                'ordering': ['-reading_time'],
            },
        ),
    ]
