# Generated by Django 5.2.6 on 2026-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0045_remove_requestfueldispensingdetails_user_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelsensorreadings',
            options={'verbose_name': 'Fuel Sensor Reading', 'verbose_name_plural': 'Fuel Sensor Readings'},
        ),
        migrations.RemoveField(
            model_name='fuelsensorreadings',
            name='reading_time',
        ),
    ]
