# Generated by Django 5.2.6 on 2026-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0046_alter_fuelsensorreadings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsensorreadings',
            name='epoch_time',
            field=models.BigIntegerField(blank=True, help_text='Unix epoch time sent from device (seconds or milliseconds)', null=True),
        ),
        migrations.AddField(
            model_name='fuelsensorreadings',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID', max_length=255, null=True),
        ),
    ]
