# Generated by Django 5.2.6 on 2026-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0048_orderfueldispensingdetails_user_tag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='user_tag_id',
            field=models.CharField(blank=True, help_text='User Tag ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='user_valid',
            field=models.BooleanField(default=False),
        ),
    ]
