# Generated by Django 5.2.6 on 2026-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0049_requestfueldispensingdetails_user_tag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='obd_sensor',
            field=models.BooleanField(default=False, help_text='Whether the vehicle is installed with obd sensor or not'),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='odometer_mac_id',
            field=models.CharField(blank=True, db_comment='MAC ID of the odometer device', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Odometer Reading', null=True),
        ),
        migrations.AlterField(
            model_name='orderfueldispensingdetails',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'Volume'), (1, 'Amount'), (2, 'Full Tank Mode')], default=0, help_text='Request Type'),
        ),
        migrations.AlterField(
            model_name='requestfueldispensingdetails',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'Volume'), (1, 'Amount'), (2, 'Full Tank Mode')], default=0, help_text='Request Type'),
        ),
    ]
