# Generated by Django 5.2.6 on 2026-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0050_dispenser_gun_mapping_to_vehicles_obd_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='latest_obd_data',
            field=models.JSONField(blank=True, help_text='Latest data received from the obd sensor', null=True),
        ),
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='live_odometer_reading',
            field=models.BigIntegerField(blank=True, help_text=';Live Odometer Reading', null=True),
        ),
    ]
