# Generated by Django 5.2.6 on 2026-05-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0051_dispenser_gun_mapping_to_vehicles_latest_obd_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenser_gun_mapping_to_vehicles',
            name='live_odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Live Odometer Reading', null=True),
        ),
        migrations.CreateModel(
            name='VehicleOBDAndGPSReadings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obd_valid', models.BooleanField(default=False, help_text='Whether the OBD data received is valid')),
                ('obd_data', models.JSONField(blank=True, help_text='Raw OBD data payload from the device as JSON', null=True)),
                ('dist_dtc', models.BigIntegerField(blank=True, help_text='Distance since DTC (Diagnostic Trouble Code) cleared, in meters', null=True)),
                ('gps_data', models.JSONField(blank=True, help_text="GPS coordinates as JSON: {'lat': ..., 'lon': ..., 'alt_m': ..., 'speed_kmh': ..., 'course_deg': ...}", null=True)),
                ('has_fix', models.BooleanField(default=False, help_text='Whether the GPS had a valid fix at the time of reading')),
                ('epoch_time', models.BigIntegerField(blank=True, help_text='Unix epoch time sent from device (seconds or milliseconds)', null=True)),
                ('dispenser_vehicle_mapping', models.ForeignKey(blank=True, help_text='Dispenser-Gun-Vehicle mapping that reported this reading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obd_gps_readings', to='IoT_Panel.dispenser_gun_mapping_to_vehicles')),
            ],
            options={
                'verbose_name': 'Vehicle OBD & GPS Reading',
                'verbose_name_plural': 'Vehicle OBD & GPS Readings',
                'db_table': 'vehicle_obd_and_gps_readings',
            },
        ),
    ]
