# Generated by Django 5.2.6 on 2026-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0052_alter_dispenser_gun_mapping_to_vehicles_live_odometer_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleobdandgpsreadings',
            name='dist_dtc',
        ),
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='obd_data',
            field=models.JSONField(blank=True, help_text='Raw OBD data payload from the device as JSON', null=True),
        ),
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Live odometer reading', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='obd_data',
            field=models.JSONField(blank=True, help_text='Raw OBD data payload from the device as JSON', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Live odometer reading', null=True),
        ),
    ]
