# Generated by Django 5.2.6 on 2026-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0053_remove_vehicleobdandgpsreadings_dist_dtc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfueldispensingdetails',
            name='odometer_reading',
        ),
        migrations.RemoveField(
            model_name='requestfueldispensingdetails',
            name='odometer_reading',
        ),
        migrations.AddField(
            model_name='vehicleobdandgpsreadings',
            name='live_odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Live Odometer Reading', null=True),
        ),
    ]
