# Generated by Django 5.2.6 on 2026-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0054_remove_orderfueldispensingdetails_odometer_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfueldispensingdetails',
            name='live_odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Live odometer reading', null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='live_odometer_reading',
            field=models.BigIntegerField(blank=True, help_text='Live odometer reading', null=True),
        ),
    ]
