# Generated by Django 5.2.6 on 2026-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0055_orderfueldispensingdetails_live_odometer_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser_gun_mapping_to_customer',
            name='gun_status',
            field=models.CharField(choices=[('unavailable', 'Unavailable'), ('online', 'Online'), ('offline', 'Offline')], default='unavailable', help_text='Gun reachability from msg_type 4 `gstatus`: active -> online, inactive -> offline, key absent -> unavailable', max_length=12),
        ),
        migrations.AlterField(
            model_name='fuelsensorreadings',
            name='data_type',
            field=models.IntegerField(choices=[(41, 'Transaction Data'), (31, '30 Sec Auto Push'), (4, 'Status Push')], help_text='41 - Transaction Data, 31 - 30 sec Auto Push'),
        ),
    ]
