# Generated by Django 5.2.6 on 2026-10-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Panel', '0056_dispenser_gun_mapping_to_customer_gun_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='latest_snapshot_path',
            field=models.CharField(blank=True, help_text='Static media path of the newest camera snapshot, e.g. /media/camera_snapshots/...jpg', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requestfueldispensingdetails',
            name='snapshot_count',
            field=models.IntegerField(default=0, help_text='Number of camera snapshots saved for this request'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(help_text='Camera serial number', max_length=100, unique=True)),
                ('model_number', models.CharField(help_text='Camera model number', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Camera brand', max_length=100, null=True)),
                ('rtmp_path', models.CharField(help_text='MediaMTX path the camera publishes to, e.g. rtmp_push/D001', max_length=150, unique=True)),
                ('webrtc_url', models.CharField(help_text='WebRTC page URL, e.g. https://cam.myaccess.cloud/rtmp_push/D001/', max_length=255)),
                ('stream_mode', models.IntegerField(choices=[(0, 'On Demand'), (1, 'Always On'), (2, 'Disabled')], default=0, help_text='On Demand: enabled only while a session needs it')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive cameras are never enabled')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dispenser_unit', models.ForeignKey(help_text='Dispenser unit the camera is installed on', on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='IoT_Panel.dispenserunits')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=40)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='IoT_Panel.camera')),
            ],
            options={
                'verbose_name': 'Camera Event',
                'verbose_name_plural': 'Camera Events',
                'db_table': 'camera_events',
            },
        ),
        migrations.CreateModel(
            name='CameraStreamSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('live_view', 'Live View'), ('fuel_request', 'Fuel Request'), ('manual', 'Manual')], max_length=20)),
                ('user_id', models.BigIntegerField(blank=True, help_text='User who opened the session', null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('closed', 'Closed'), ('timeout', 'Timeout'), ('request_completed', 'Request Completed'), ('request_interrupted', 'Request Interrupted'), ('request_failed', 'Request Failed'), ('manual_disable', 'Manual Disable'), ('camera_deleted', 'Camera Deleted'), ('camera_edited', 'Camera Edited')], max_length=30, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='IoT_Panel.camera')),
                ('dispenser_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_sessions', to='IoT_Panel.dispenserunits')),
                ('order_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_sessions', to='IoT_Panel.orderfueldispensingdetails')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_sessions', to='IoT_Panel.requestfueldispensingdetails')),
            ],
            options={
                'verbose_name': 'Camera Stream Session',
                'verbose_name_plural': 'Camera Stream Sessions',
                'db_table': 'camera_stream_sessions',
            },
        ),
        migrations.CreateModel(
            name='RequestCameraSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('dispenser_serialnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('dispenser_imeinumber', models.CharField(blank=True, max_length=255, null=True)),
                ('dispenser_gun_mapping_id', models.BigIntegerField(blank=True, null=True)),
                ('request_status', models.IntegerField(blank=True, help_text='Request status at capture (0 Pending ... 5 Failed)', null=True)),
                ('dispense_status_code', models.IntegerField(blank=True, help_text='Raw hardware status code at capture', null=True)),
                ('dispensed_volume', models.FloatField(blank=True, null=True)),
                ('dispensed_amount', models.FloatField(blank=True, null=True)),
                ('gps_coordinates', models.JSONField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('periodic', 'Periodic'), ('stage', 'Stage')], default='periodic', max_length=10)),
                ('image_path', models.CharField(help_text='Static media path, e.g. /media/camera_snapshots/2026/10/03/<txn>/<uuid>.jpg', max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField()),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='IoT_Panel.camera')),
                ('dispenser_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_snapshots', to='IoT_Panel.dispenserunits')),
                ('order_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_snapshots', to='IoT_Panel.orderfueldispensingdetails')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_snapshots', to='IoT_Panel.requestfueldispensingdetails')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='IoT_Panel.camerastreamsession')),
            ],
            options={
                'verbose_name': 'Request Camera Snapshot',
                'verbose_name_plural': 'Request Camera Snapshots',
                'db_table': 'request_camera_snapshots',
                'indexes': [models.Index(fields=['request', 'captured_at'], name='rcs_request_captured_idx'), models.Index(fields=['transaction_id', 'captured_at'], name='rcs_txn_captured_idx'), models.Index(fields=['dispenser_unit', 'captured_at'], name='rcs_dispenser_captured_idx')],
            },
        ),
    ]
