# Generated by Django 5.2.6 on 2025-09-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existing_tables', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylocations',
            options={'managed': True},
        ),
    ]
