# Generated by Django 5.2.6 on 2025-09-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existing_tables', '0003_alter_deliverylocations_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocations',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='deliverylocations',
            name='main_area',
        ),
        migrations.RemoveField(
            model_name='deliverylocations',
            name='save_as',
        ),
        migrations.AddField(
            model_name='deliverylocations',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='existing_tables.customers'),
        ),
        migrations.AddField(
            model_name='deliverylocations',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='existing_tables.organizations'),
        ),
        migrations.AddField(
            model_name='deliverylocations',
            name='primary_sourcing_outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='existing_tables.partneroutlets'),
        ),
        migrations.AddField(
            model_name='deliverylocations',
            name='sub_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='existing_tables.subclusters'),
        ),
        migrations.AlterField(
            model_name='deliverylocations',
            name='company_latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliverylocations',
            name='company_longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
