# Generated by Django 5.2.6 on 2025-10-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existing_tables', '0004_remove_deliverylocations_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_types',
                'managed': False,
            },
        ),
    ]
